Repository Fraunhofer-AISEC/cpg, pull requests merged in 2020-07, with the labels that each got.

#145 Fix: MemberCalls with MemberExpressions
  src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
  src/test/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.java
  src/test/resources/compiling/MemberCallExpression.java
Labels: bug

#146 Fix: Field "fqn" of CallExpression/MemberCallExpression must not contain modifiers "*" or "[]" for PointerTypes
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/CallExpression.java
Labels: bug

#155 Correctly connecting field references in C++ method definitions
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclaratorHandler.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/ExpressionHandler.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/FunctionDeclaration.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/RecordDeclaration.java
  src/main/java/de/fraunhofer/aisec/cpg/helpers/SubgraphWalker.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java
  src/test/java/de/fraunhofer/aisec/cpg/TypeTests.java
  src/test/java/de/fraunhofer/aisec/cpg/enhancements/variable_resolution/VariableResolverCppTest.java
  src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
  src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontendTest.java
  src/test/resources/include.cpp
  src/test/resources/include.h
  src/test/resources/recordstmt.cpp
Labels: cxx, help wanted

#163 Type hierarchy (for Java)
  src/main/java/de/fraunhofer/aisec/cpg/TranslationConfiguration.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/type/Type.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/type/UnknownType.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/JavaExternalTypeHierarchyResolver.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/TypeResolver.java
  src/main/java/de/fraunhofer/aisec/cpg/processing/strategy/Strategy.java
  src/test/java/de/fraunhofer/aisec/cpg/TypeTests.java
  src/test/java/de/fraunhofer/aisec/cpg/frontends/java/DemoTests.java
  src/test/resources/compiling/hierarchy/multistep/Level0.java
  src/test/resources/compiling/hierarchy/multistep/Level1.java
  src/test/resources/compiling/hierarchy/multistep/Level1B.java
  src/test/resources/compiling/hierarchy/multistep/Level2.java
  src/test/resources/compiling/hierarchy/multistep/Root.java
  src/test/resources/compiling/hierarchy/multistep/Unrelated.java
Labels: enhancement, java

#180 Performance tweaks
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/Expression.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
Labels: quirk

#182 Restored documented behaviour of loadIncludes
  src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/Expression.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/TranslationUnitDeclaration.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java
  src/test/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXIncludeTest.java
Labels: discussion
