Repository Fraunhofer-AISEC/cpg, pull requests merged in 2021-03, with the labels that each got.

#352 CallResolver Refinement for Calls with Implicit Cast
  src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/FunctionDeclaration.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/edge/PropertyEdge.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/CallExpression.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/types/ObjectType.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/types/Type.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
  src/test/java/de/fraunhofer/aisec/cpg/enhancements/calls/CallResolverTest.java
  src/test/resources/calls/implicitcast/ambiguouscall.cpp
  src/test/resources/calls/implicitcast/implicitcast.cpp
Labels: cxx

#350 Initial Go Language support
  .github/workflows/build.yml
  .gitignore
  README.md
  go-jni/.vscode/tasks.json
  go-jni/basic_types.go
  go-jni/build.sh
  go-jni/declarations.go
  go-jni/expressions.go
  go-jni/frontend/frontend.go
  go-jni/frontend/handler.go
  go-jni/go.mod
  go-jni/go.sum
  go-jni/language.go
  go-jni/lib/cpg/main.go
  go-jni/node.go
  go-jni/scope.go
  go-jni/statements.go
  go-jni/types.go
  src/main/java/de/fraunhofer/aisec/cpg/ExperimentalGolang.kt
  src/main/java/de/fraunhofer/aisec/cpg/ExperimentalGraph.kt
  src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontendFactory.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontend.kt
  src/main/java/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.java
  src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontend.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/NodeBuilder.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/MethodDeclaration.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/declarations/TranslationUnitDeclaration.java
  src/main/java/de/fraunhofer/aisec/cpg/graph/types/ObjectType.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/CallResolver.java
  src/main/java/de/fraunhofer/aisec/cpg/passes/scopes/ScopeManager.java
  src/test/java/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
  src/test/resources/golang/construct.go
  src/test/resources/golang/field.go
  src/test/resources/golang/function.go
  src/test/resources/golang/go.mod
  src/test/resources/golang/if.go
  src/test/resources/golang/literal.go
  src/test/resources/golang/struct.go
  src/test/resources/golang/switch.go
Labels: experimental, go

#359 Making gradle build go
  .github/workflows/build.yml
  README.md
  build.gradle.kts
  src/main/golang/.vscode/tasks.json
  src/main/golang/basic_types.go
  src/main/golang/build.sh
  src/main/golang/declarations.go
  src/main/golang/expressions.go
  src/main/golang/frontend/frontend.go
  src/main/golang/frontend/handler.go
  src/main/golang/go.mod
  src/main/golang/go.sum
  src/main/golang/language.go
  src/main/golang/lib/cpg/main.go
  src/main/golang/node.go
  src/main/golang/scope.go
  src/main/golang/statements.go
  src/main/golang/types.go
  src/test/java/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
Labels: ci, go
