Repository Fraunhofer-AISEC/cpg, pull requests merged in 2022-05, with the labels that each got.

#777 Fix detection of multiple typedef statement
  cpg-core/src/main/java/de/fraunhofer/aisec/cpg/helpers/Util.java
  cpg-core/src/test/java/de/fraunhofer/aisec/cpg/enhancements/TypedefTest.java
  cpg-core/src/test/resources/typedefs/typedefs.cpp
Labels: bug, cxx

#784 Fixed missing DFG edges in Go frontend
  cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/Extensions.kt
  cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/statements/expressions/InitializerListExpression.java
  cpg-language-go/src/main/golang/expressions.go
  cpg-language-go/src/main/golang/frontend/handler.go
  cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
  cpg-language-go/src/test/resources/golang/dfg.go
  cpg-language-go/src/test/resources/golang/values.go
Labels: go

#787 Fixing javadoc error in JitPack build
  cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/HasType.java
Labels: ci
