Repository Fraunhofer-AISEC/cpg, pull requests merged in 2024-03, with the labels that each got.

#1331 More improvements to the Go frontend
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/ScopeManager.kt
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/DynamicInvokeResolver.kt
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/inference/Inference.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoHandler.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguage.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontend.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoStandardLibrary.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoUtils.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/SpecificationHandler.kt
  cpg-language-go/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/GoExtraPass.kt
  cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/GoLanguageFrontendTest.kt
  cpg-language-go/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/golang/IntegrationTest.kt
  cpg-language-go/src/test/resources/golang/complex_resolution/calls/calls.go
  cpg-language-go/src/test/resources/golang/literal.go
  cpg-language-go/src/test/resources/golang/packages/api/apiv1.go
  cpg-language-go/src/test/resources/golang/packages/cmd/packages/packages.go
  cpg-language-go/src/test/resources/golang/packages/packages.go
  cpg-language-go/src/test/resources/golang/types.go
Labels: go

#1450 Add members, methods and imports to EnumDeclarations
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/Language.kt
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ImportResolver.kt
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/SymbolResolver.kt
  cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
  cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/ExpressionHandler.kt
  cpg-language-java/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguageFrontendTest.kt
  cpg-language-java/src/test/resources/compiling/enums/Enums.java
  cpg-language-java/src/test/resources/compiling/enums/EnumsImport.java
Labels: java

#1469 Adds pass dependencies for `EdgeCachePass`
  cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/EdgeCachePass.kt
Labels: bug
